project_id = "duzgvkljbwtocgydbbln"

[functions.process-csv-products]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.gpt-commerce-agent]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.shift-agent]
verify_jwt = false

[functions.shift-import-catalog]
verify_jwt = false

[functions.shift-embed-products]
verify_jwt = false